name: Publish Packages
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Get release version
        id: get_version
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:11})

      - name: Publish check
        run: |
          ver=$RELEASE_VERSION
          check_pkg() {
            curl -sL "http://registry.npmjs.com/@pipcook/$1" | jq -r '.versions."'$2'".version'
          }

          check_image() {
            curl -sL "https://hub.docker.com/v2/repositories/pipcook/pipcook/tags/$1" | jq -r '.name'
          }

          if
            [ $(check_pkg pipcook-cli $ver) == $ver ] &&
            [ $(check_pkg daemon $ver) == $ver ]
          then
            echo ::set-env name=NPM_PUBLISHED::true
          fi

          if [ $(check_image $ver) == $ver ]; then
            echo ::set-env name=DOCKER_PUBLISHED::true
          fi

      - name: Publish to Docker registry
        uses: docker/build-push-action@v1
        if: env.DOCKER_PUBLISHED != 'true'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: liangzr/test_github_workflow
          dockerfile: docker/Dockerfile
          build_args: VER=${{ env.RELEASE_VERSION }}
          tags: "latest,${{ env.RELEASE_VERSION }}"