name: Deploy Docker image
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      # - name: Build image
      #   run: ./docker/build.sh
        
      - name: Get release version
        id: get_version
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:11})

      - name: Publish to registry
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: liangzr/test_github_workflow
          dockerfile: docker/Dockerfile
          build_args: VER=${{ env.RELEASE_VERSION }}
          tags: "latest,${{ env.RELEASE_VERSION }}"
