name: Deploy Docker image
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build image
        run: ./docker/build.sh
        
      - name: Get release version
        id: get_version
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:11})

      - name: Publish to registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: liangzr/test_github_workflow
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,${{ env.RELEASE_VERSION }}"
