name: CI

on:
  push:
    tags:
      - 'v*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Build image
      run: |
        docker

    # Runs a set of commands using the runners shell
    - name: Publish to Docker hub
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
